language: node_js
node_js: "lts/*"
install: yarn
script: yarn build
branches:
  only:
  - master
deploy:
  provider: pages
  edge:
    branch: pages-ivar-set
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: build